In [42]:
# http://www.bogotobogo.com/python/Flask/Python_Flask_Embedding_Machine_Learning_1.php

In [43]:
import pickle
import re
import os
from vectorizer import vect
clf = pickle.load(open(os.path.join('pkl_objects', 'classifier.pkl'), 'rb'))

In [44]:
clf

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', n_iter=1, n_jobs=1,
       penalty='l2', power_t=0.5, random_state=1, shuffle=True, verbose=0,
       warm_start=False)

In [45]:
import numpy as np
label = {0:'negative', 1:'positive'}

In [46]:
example = ['I love this movie a lot']
X = vect.transform(example)
X

<1x2097152 sparse matrix of type '<type 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [47]:
clf.predict(X)

array([1])

In [48]:
clf.predict(X)[0]

1

In [49]:
clf.predict_proba(X)

array([[ 0.1817794,  0.8182206]])

In [50]:
label[clf.predict(X)[0]], np.max(clf.predict_proba(X))*100

('positive', 81.822059513044678)

In [51]:
# More Sentiment Analysis - Negetive Review

In [52]:
import numpy as np
label = {0:'negative', 1:'positive'}
example = ['I hate this movie']
X = vect.transform(example)
clf.predict_proba(X)

array([[ 0.67270865,  0.32729135]])

In [53]:
label[clf.predict(X)[0]], np.max(clf.predict_proba(X))*100

('negative', 67.270864651747914)

In [54]:
import numpy as np
label = {0:'negative', 1:'positive'}
example = ['The movie was really terrible and awful']
X = vect.transform(example)

In [55]:
clf.predict_proba(X)

array([[ 0.99336116,  0.00663884]])

In [56]:
label[clf.predict(X)[0]], np.max(clf.predict_proba(X))*100

('negative', 99.336116282043989)

In [57]:
# More Sentiment Analysis - Favorable Review

In [58]:
import numpy as np
label = {0:'negative', 1:'positive'}
example = ['Amazing, this movie is the best ever']
X = vect.transform(example)

In [59]:
clf.predict_proba(X)

array([[ 0.04785583,  0.95214417]])

In [60]:
label[clf.predict(X)[0]], np.max(clf.predict_proba(X))*100

('positive', 95.21441701567484)

In [61]:
# SQLite setup

In [64]:
import sqlite3
import os

conn = sqlite3.connect('reviews.sqlite')
c = conn.cursor()
'''
c.execute('CREATE TABLE review_db'\
        ' (review TEXT, sentiment INTEGER, date TEXT)')

example1 = 'I love this movie'
c.execute("INSERT INTO review_db"\
        " (review, sentiment, date) VALUES"\
        " (?, ?, DATETIME('now'))", (example1, 1))

example2 = 'I disliked this movie'
c.execute("INSERT INTO review_db"\
        " (review, sentiment, date) VALUES"\
        " (?, ?, DATETIME('now'))", (example2, 0))

conn.commit()
conn.close()
'''

'\nc.execute(\'CREATE TABLE review_db\'        \' (review TEXT, sentiment INTEGER, date TEXT)\')\n\nexample1 = \'I love this movie\'\nc.execute("INSERT INTO review_db"        " (review, sentiment, date) VALUES"        " (?, ?, DATETIME(\'now\'))", (example1, 1))\n\nexample2 = \'I disliked this movie\'\nc.execute("INSERT INTO review_db"        " (review, sentiment, date) VALUES"        " (?, ?, DATETIME(\'now\'))", (example2, 0))\n\nconn.commit()\nconn.close()\n'

In [34]:
# Reconenct to check if the reviews have been successfuly stored

In [36]:
conn = sqlite3.connect('reviews.sqlite')
c = conn.cursor()
c.execute("SELECT * FROM review_db WHERE date"\
        " BETWEEN '2016-11-01 00:00:00' AND DATETIME('now')")
results = c.fetchall()
conn.close()
results

[(u'I love this movie', 1, u'2016-11-03 15:55:12'),
 (u'I disliked this movie', 0, u'2016-11-03 15:55:12')]